name: UNIT-TEST

# Controls when the action will run.
on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      - name: set-node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependence for core
        run: |
          npm ci
        working-directory: './core'

      - name: Run Tests
        working-directory: './shell'
        run: |
          npm ci
          npm run test:coverage
          npm run copy:coverage

      - name: Codecov
        uses: codecov/codecov-action@v1.4.1
        with:
          file: ./coverage.yml
