name: UNIT-TEST

# Controls when the action will run.
on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      - name: install dependence for core
        working-directory: './core'
        run：npm install

      - name: Run Tests
        working-directory: './shell'
        uses: anna-money/github-actions-npm@v2
        with:
          target: 'test:coverage'


      - name: Codecov
        working-directory: './shell'
        uses: codecov/codecov-action@v1.4.1
